name: 'Markdown to GitHub Pages Deploy'
description: 'Convert Markdown files to HTML with Pandoc and deploy to GitHub Pages.'
author: 'Godners-Code'
branding:
  icon: 'upload'
  color: 'blue'

inputs:
  page-title:
    description: 'Page Title (Defaults as Repository Name)'
    required: false
    default: ${{ github.event.repository.name }}
  image-src:
    description: 'Source Images Path (Default as "Images")'
    required: false
    default: 'Images'
  image-dst:
    description: 'Destination Image Path (Default as "Images")'
    required: false
    default: 'Images'
  home-target:
    description: 'Source HomePage Path (Default as "./README.html")'
    required: false
    default: './README.html'
  icons-src:
    description: 'Source Icon Path (Default as "favicon.jpg")'
    required: false
    default: 'favicon.jpg'
  robot-src:
    description: 'Source robots.txt Path (Default as "robots.txt")'
    required: false
    default: 'robots.txt'
  ex-dir:
    description: 'Exclude Paths (Embedded _site, .git, .github)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: "[STEP] Setup Pandoc"
      uses: pandoc/actions/setup@main

    - name: "[STEP] Setup Python"
      uses: actions/setup-python@main

    - name: "[STEP] Install Dependencies"
      shell: bash
      run: pip install --upgrade pip jinja2

    - name: "[STEP] Run Deploy Script"
      shell: bash
      run: python ${{ github.action_path }}/deploy.py
      env:
        INPUT_PAGE_TITLE: ${{ inputs.page-title }}
        INPUT_IMAGE_SRC: ${{ inputs.image-src }}
        INPUT_IMAGE_DST: ${{ inputs.image-dst }}
        INPUT_HOME_SRC: ${{ inputs.home-target }}
        INPUT_ICONS_SRC: ${{ inputs.icons-src }}
        INPUT_ROBOT_SRC: ${{ inputs.robot-src }}
        INPUT_EX_DIR: ${{ inputs.ex-dir }}

    - name: "[STEP] Setup Pages"
      uses: actions/configure-pages@main

    - name: "[STEP] Upload Artifact"
      id: upload-artifact
      uses: actions/upload-pages-artifact@main
      with:
        path: ./_site

    - name: "[STEP] Deploy to GitHub Pages"
      id: deployment
      uses: actions/deploy-pages@main
